name: Resyntax

on:
  # See https://github.community/t/github-actions-are-severely-limited-on-prs/18179 for
  # why this uses pull_request_target instead of pull_request
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          # See https://github.com/actions/checkout/issues/118 for why the fetch depth needs to be zero
          fetch-depth: 0
          # See https://github.community/t/github-actions-are-severely-limited-on-prs/18179/17 for why
          # we need to specify the ref to checkout
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: Bogdanp/setup-racket@v1.8.1
        with:
          version: current
          packages: resyntax
          local_catalogs: $GITHUB_WORKSPACE
          dest: '"${HOME}/racketdist-current-CS"'
          sudo: never
      - name: Register local packages
        run: |
          raco pkg install -i --auto --no-setup --skip-installed typed-racket-test
          raco pkg update --auto --no-setup source-syntax typed-racket-lib typed-racket-more typed-racket-compatibility typed-racket-doc typed-racket typed-racket-test
      - run: raco setup typed typed-racket typed-racket-test typed-scheme
      - run: xvfb-run racket -l- resyntax/cli analyze --local-git-repository . "origin/${GITHUB_BASE_REF}" --output-as-github-review
